spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  mail:
    host: smtp.example.com
    port: 587
    username: "test@example.com"
    password: "password"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
