services:

  messages-sender:
    image: messages-sender:1.0.0
    build:
      context: ../../messages-sender
      dockerfile: Dockerfile
    container_name: messages-sender
    networks:
      - simple-messaging-gateway-network
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - mailhog

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - simple-messaging-gateway-network

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    restart: always
    networks:
      - simple-messaging-gateway-network
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  rabbitmq_data:

networks:
  simple-messaging-gateway-network:
